### ISSUE TITLE
Error in shxarray for ICGEM format

### ISSUE THREAD

**Issue by SedighehKarimi** [ITC-Water-Resources/shxarray#2]
I am facing an issue when using the `sh.tws()` for a dataset in the ICGEM format with the following code:

`import numpy as np
import pandas as pd
import xarray as xr
import shxarray

# Creating Sample Data with a similar structure as icgem

time_dim = 20
nmax = 60
n = []
m = []

for i in range(nmax + 1):
    n.extend([i] * (2 * i + 1))
    if i == 0:
        m.append(0)  
    else:
        m.append(0)  
        for j in range(1, i + 1):
            m.extend([j, -j])  

n = np.array(n)
m = np.array(m)
time = pd.date_range("2002-04-15", periods=time_dim, freq="M")
nm_index = pd.MultiIndex.from_arrays([n, m], names=("n", "m"))
cnm_data = np.random.randn(time_dim, len(nm_index)) * 1e-9  

ds = xr.Dataset({"cnm": (["time", "nm"], cnm_data),},coords={"time": time,"nm": nm_index})

datws=ds.cnm.sh.tws()`

**Comment by strawpants** [comment]
Hi Kiana,
is there a  particular error you're getting?
FYI you can zero-initialize a xarray structure with a valid nm index and auxiliary dimensions with e.g.

`ds=xr.sh.zeros(nmax,auxcoords={"time":time})`

**Comment by SedighehKarimi** [comment]
Hi Roelof,
I got the error `Requested kernel operation is only supported for degrees {nminsup} < = n <= {nmaxsup}` when calling `sh.tws()`, which was due to mistakenly including n and m = 0 in the xarray structure. Excluding this degree resolved the issue and the function runs without errors.

**Comment by strawpants** [comment]
Mark as solved as this was related to another problem
